Update PDR processing to respect NODE_NAME parameter
nasa/cumulus pull request #1860
Opened 2020-09-10 19:00 UTC by yjpa7145

**Summary:** Update PDR processing to respect NODE_NAME parameter

Addresses [CUMULUS-2141: PDR processing not respecting NODE_NAME parameter](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2141)

## Changes

* Detailed list or prose of changes
* ...

## PR Checklist

- [ ] Update CHANGELOG
- [ ] Unit tests
- [ ] Adhoc testing
- [ ] Integration tests

2020-09-17 05:29 UTC, Jkovarik requested changes
This looks good - I've added a few comments for discussion and there's a couple of style/nit considerations.

2020-09-18 20:10 UTC, yjpa7145 commented on example/spec/parallel/ingest/ingestPdrWithNodeNameSpec.js
> +      const createProviderResponse = await providersApi.createProvider({
440c1159e

2020-09-18 20:10 UTC, yjpa7145 commented on packages/api-client/src/providers.ts
>   */
d571987ee

2020-09-18 20:10 UTC, yjpa7145 commented on tasks/queue-granules/index.js
> +        provider: granule.provider || event.config.provider,
Probably, but that feels like a separate ticket.

2020-09-18 20:10 UTC, yjpa7145 commented on tasks/parse-pdr/tests/test-parse-pdr.js
> +  const hdfFile = granule.files.find((file) => file.name === 'MOD09GQ.A2017224.h09v02.006.2017227165020.hdf');
I really don't have strong feelings either way on this one.

2020-09-18 20:15 UTC, Jkovarik commented on tasks/parse-pdr/tests/test-parse-pdr.js
> +  const hdfFile = granule.files.find((file) => file.name === 'MOD09GQ.A2017224.h09v02.006.2017227165020.hdf');
That sounds like not near-immediate feelings of awesomeness.   👍

2020-09-18 20:18 UTC, Jkovarik commented on example/spec/parallel/ingest/ingestPdrWithNodeNameSpec.js
> +          expect(queuePdrsOutput.payload.pdrs_queued).toEqual(1);
Low-effort follow-up to this: https://github.com/nasa/cumulus/pull/1875.   Will write a quick maintenance ticket to address the overall issue.

2020-09-18 20:20 UTC, Jkovarik approved these changes
Thanks, that addresses my concerns.   One thing outstanding is getting the updated variables into bamboo/set-bamboo-env-variables.   Approving assuming that's sorted and CI works.

2020-09-21 17:35 UTC, merged