Update logging docs
nasa/cumulus pull request #1936
Opened 2020-10-15 14:01 UTC by markdboyd

Fixing some docs that didn't get properly updated for the move to deploying TEA as a separate module

2020-10-15 20:40 UTC, nemreid approved these changes
LGTM

2020-10-22 18:10 UTC, laurenfrederick requested changes

2020-10-22 18:10 UTC, laurenfrederick commented on docs/deployment/README.md
> -### Create a secret for signing Thin Egress App JWTs
In the template deploy we still have `thin_egress_app` in the cumulus-tf deployment, which needs this. I think it should either be removed from there and the docs updated on how to do a distribution deployment or this should stay.

2020-10-22 18:10 UTC, laurenfrederick commented on docs/deployment/README.md
> -### Create a secret for signing Thin Egress App JWTs
I am thinking have this stay and update the deployment docs to call out the configuration. I am making deployment doc updates so can do that. What do you think?

2020-10-22 19:16 UTC, laurenfrederick approved these changes

2020-10-23 22:16 UTC, merged