[CUMULUS-2344] Remove some restrictions from ES endpoints
nasa/cumulus pull request #2045
Opened 2021-01-13 18:54 UTC by bt6453

**Summary:** Summary of changes

Addresses [CUMULUS-2344: Allow reindexing to an existing index(https://bugs.earthdata.nasa.gov/browse/CUMULUS-2344)

## Changes

* The reindex endpoint will allow you to reindex to an endpoint that already exists
* The change-index endpoint will allow you to change to index that does not
  exist. If it doesn't exist it will be created for you.

## PR Checklist

- [ ] Update CHANGELOG
- [ ] Unit tests
- [ ] Adhoc testing
- [ ] Integration tests

2021-01-14 18:49 UTC, laurenfrederick requested changes
I have an issue doing the `change-index`, then the `reindex`. On line 82 the `reindex` operation checks that the `sourceIndex` is aliased under the alias. After you do the change-index it's not under the alias anymore. I don't _think_ we need this check there, but haven't had time to completely think through it.

2021-01-14 21:17 UTC, bt6453 commented
Yeah I'm not sure I understand completely what the alias checks are for. I think users should be able to reindex to any index they want just like using the ES API directly BUT I understand there might be need for some safety checks.

2021-01-20 21:14 UTC, bt6453 commented
Added a reindexing guide and removed the restrictions around changing index and reindexing.

2021-01-20 21:39 UTC, bt6453 commented
API docs updates PR: https://github.com/nasa/cumulus-api/pull/296

2021-01-25 15:36 UTC, laurenfrederick requested changes

2021-01-25 15:36 UTC, laurenfrederick commented on docs/troubleshooting/reindex-elasticsearch.md
> +## Change Index and Reindex
```suggestion
## Switch to a new index and reindex
```

2021-01-25 15:36 UTC, laurenfrederick commented on docs/troubleshooting/reindex-elasticsearch.md
> +It is recommended to change Cumulus to point to an empty index first. This will allow new data to be passed to the index without
Mention that this step will create a new index for you

2021-01-25 15:36 UTC, laurenfrederick commented on docs/troubleshooting/reindex-elasticsearch.md
> +The first way involves reindexing from the existing Elasticsearch index to a brand new index. This is done in two steps.
We need to mention that for a period of time, while the reindex takes place, you will not see all of your data on the dashboard as it being brought over from the previous index. We should mention both options here. 1. you use the new index and the pros are you don't lose data, but the cons are it messes with your dashboard. 2. you reindex, then switch and the pros are your dashboard looks good, cons are you should stop ingest.

2021-01-25 15:36 UTC, laurenfrederick commented on docs/troubleshooting/reindex-elasticsearch.md
> +current index, or the mappings for an index have been updated (they do not update automatically), there are two ways
Mention that a reindex due to mappings changing will be called out in the Migration Steps of the changelog.

2021-01-26 19:24 UTC, bt6453 commented
Updated with your recommendations.

2021-01-27 15:21 UTC, laurenfrederick approved these changes

2021-01-27 15:27 UTC, merged