Update CHANGELOG with warnings about TEA deployment
nasa/cumulus pull request #2077
Opened 2021-02-05 16:31 UTC by markdboyd

2021-02-05 17:24 UTC, botanical commented on CHANGELOG.md
> +  For now, the workaround if you see this issue is to manually delete the `<prefix>-tf-TeaCache`, which will fix the race condition issue and allow you to deploy.
```suggestion
  For now, the workaround if you see this issue is to manually delete the `<prefix>-tf-TeaCache`, which will fix the race condition issue and allow you to successfully deploy.
```

2021-02-05 17:26 UTC, botanical commented on CHANGELOG.md
> +  ```shell
Does "```shell" work differently in markdown? It seems to render the code as a single long line.

2021-02-05 17:28 UTC, markdboyd commented on CHANGELOG.md
> +  ```shell
I can add some line breaks

2021-02-05 17:43 UTC, botanical approved these changes
Thanks for updating this!

2021-02-09 13:46 UTC, Jkovarik requested changes
I have a fix for this.  We should *not* merge this PR.

2021-02-11 15:10 UTC, markdboyd commented
Superseded by #2083

2021-02-11 15:10 UTC, closed without merging