HYRAX-357
nasa/cumulus pull request #2136
Opened 2021-03-10 19:27 UTC by laurenfrederick

**Summary:** Updated hyrax-metadata-updates with new OPeNDAP URL format.

Addresses [HYRAX-357:node.js development for Cumulus](https://bugs.earthdata.nasa.gov/browse/HYRAX-357?filter=-1)

From [this PR](https://github.com/nasa/cumulus/pull/2116)

## Changes

* Detailed list or prose of changes
* ...

## PR Checklist

- [ ] Update CHANGELOG
- [ ] Unit tests
- [ ] Adhoc testing
- [ ] Integration tests

2021-03-11 15:03 UTC, vskorole commented
Should not to remove getEntryTitle function in the _index.js_ because it is used in _test-integration-index.js_ and _test-search-failures.js_

2021-03-17 18:17 UTC, nemreid requested changes
I have a few small things I'd like to see addressed, then I can approve this.

2021-03-17 18:17 UTC, nemreid commented on tasks/hyrax-metadata-updates/index.js
> +    && config.addShortnameAndVersionIdToConceptId === true)
Given that this conditional checks that `config.addShortnameAndVersionIdToConceptId` is both defined AND true, can't we just strict-check for true?

2021-03-17 18:17 UTC, nemreid commented on tasks/hyrax-metadata-updates/tests/test-integration-index.js
>      });
The `beforeEach` in this test file still references the `entry title` concept.

2021-03-23 15:05 UTC, laurenfrederick reviewed
@nemreid addressed comments. Thanks for the review!

2021-03-24 17:43 UTC, nemreid approved these changes
Great 💯

2021-03-24 17:44 UTC, merged