CUMULUS-2208: Write PDRs directly to ES
nasa/cumulus pull request #2284
Opened 2021-06-11 20:19 UTC by markdboyd

**Summary:** Summary of changes

Addresses [CUMULUS-2208: Develop amazing new feature](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2208)

## Changes

* Update DB write lambda to write PDRs directly to Elasticsearch
* Move code for generating PDR from message to `message` package

## PR Checklist

- [x] Update CHANGELOG
- [x] Unit tests
- [ ] Ad-hoc testing - Deploy changes and test manually

2021-06-16 19:02 UTC, Jkovarik requested changes
Adding a couple of initial comments for review/feedback, working on deploying/manual testing/looking through the message unit.

2021-06-16 19:02 UTC, Jkovarik commented on packages/message/src/PDRs.ts
> +  return record;
having this in .ts is :100:   Nice work.

2021-06-16 19:10 UTC, Jkovarik commented
packages/api/tests/endpoints/test-pdrs.js is also failing locally/on CI due to what appears to be a missing execution fixture/mock.

2021-06-16 19:14 UTC, Jkovarik commented on packages/api/lib/testUtils.js
> +    execution: 'execution',
Adding this is blowing up the PDR endpoint test as it's trying to translate a record with this execution default in it.

2021-06-17 16:22 UTC, markdboyd commented on packages/api/lambdas/sf-event-sqs-to-db-records/write-pdr.js
> +    await pdrModel.delete({ pdrName: pdrApiRecord.pdrName });
I'm not sure I understand. Why would we add a retry?

2021-06-17 16:23 UTC, markdboyd commented on packages/api/lambdas/sf-event-sqs-to-db-records/write-pdr.js
> +    await pdrModel.storePdr(pdrApiRecord, cumulusMessage);
I'm not sure I follow. Are you saying that we could be indexing to ES the out of order record since the error is caught/trapped in storePdr?

2021-06-23 04:03 UTC, Jkovarik commented on packages/api/lib/testUtils.js
> +    // execution: 'execution',
This should be removed.

2021-06-23 04:05 UTC, Jkovarik approved these changes
I've reviewed the updates since the first review, thanks for addressing my concerns!

2021-07-19 19:41 UTC, merged