Merge master into feature branch
nasa/cumulus pull request #2443
Opened 2021-09-03 21:25 UTC by markdboyd

2021-09-07 20:16 UTC, botanical requested changes
There are a couple tests failing with 
```
migration failed with error: Invalid migration: index.js must have both an up and down function
```
which I've been able to reproduce locally 🤔

2021-09-09 22:19 UTC, botanical commented on packages/api/tests/lib/test-granule-delete.js
> -  // granule should still exist in DynamoDB and PostgreSQL
This is a nit but I prefer this comment

2021-09-09 22:19 UTC, botanical commented on packages/api/tests/lib/test-granule-delete.js
> -  // granule should still exist in DynamoDB and PostgreSQL
I think there are a few others like this as well

2021-09-09 22:25 UTC, botanical commented on packages/api/lib/writeRecords/write-granules.js
> +    // return granuleModel.storeGranule(dynamoGranuleRecord);
I believe this should be uncommented 
```suggestion
     return granuleModel.storeGranule(dynamoGranuleRecord);
```

2021-09-09 22:47 UTC, botanical commented on packages/api/lib/writeRecords/write-granules.js
> +    // return granuleModel.storeGranule(dynamoGranuleRecord);
Looking into this further, it looks like this can be removed altogether because of the storing of the granule occurs in `writeGranuleToDynamoAndEs`

2021-09-10 14:59 UTC, Jkovarik approved these changes

2021-09-10 20:09 UTC, botanical approved these changes
Thanks for addressing my feedback! Looks good to me

2021-09-13 14:31 UTC, merged