CUMULUS-2439: Add CMR search client config to CreateReconciliationReport lambda
nasa/cumulus pull request #2559
Opened 2021-11-05 19:41 UTC by jennyhliu

**Summary:** Summary of changes

Addresses [CUMULUS-2439: create-reconciliation-report not retrieving all expected collections from CMR](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2439)

## Changes

* Added CMR search client setting to the CreateReconciliationReport lambda function.
* Added `cmr_search_client_config` tfvars to the archive and cumulus terraform modules.
* Updated CreateReconciliationReport lambda to search CMR collections with CMRSearchConceptQueue.

## Test:
* Configure cmr_search_client_config in terraform.tfvars, e.g.
cmr_search_client_config = {
  create_reconciliation_report_cmr_limit = 10
  create_reconciliation_report_cmr_page_size = 5
}
* Check environment variable for prefix-CreateReconciliationReport lambda, it should have CMR_LIMIT = 10 and CMR_PAGE_SIZE = 5
* Create an inventory report, and verify that collections only in CMR are listed and > 10.

## PR Checklist

- [x] Update CHANGELOG
- [x] Unit tests
- [x] Ad-hoc testing - Deploy changes and test manually
- [ ] Integration tests

2021-11-08 22:40 UTC, jennyhliu commented on example/spec/parallel/distributionAPI/distributionTEASpec.js
> +describe('TEA Distribution API', () => {
not related to this ticket.  But TEA is still deployed and support, and we want to enable the test

2021-11-10 18:17 UTC, flamingbear requested changes
I have one change and a few questions, happy to go over them in person if you want.  Looks good though.

2021-11-10 18:17 UTC, flamingbear commented on docs/configuration/task-configuration.md
> +}
I think we should have a note or a link to the relevant CMR documentation of these variables and include that limit must be larger than page_size?

2021-11-10 19:59 UTC, jennyhliu commented on packages/api/lambdas/create-reconciliation-report.js
> +    log.error(JSON.stringify(error));
With `errorify`, deep object properties which are not part of the getOwnPropertyNames(error) are ignored. Such as `meta` isn't printed out with `errorify`.

with stringify(error):
```
{
    "level": "error",
    "message": "{\"name\":\"ResponseError\",\"meta\":{\"body\":{\"error\":{\"root_cause\":[{\"type\":\"search_context_missing_exception\",\"reason\":\"No search context found for id [10256]\"},{\"type\":\"search_context_missing_exception\",\"reason\":\"No search context found for id [10257]\"}],\"type\":\"search_phase_execution_exception\",\"reason\":\"all shards failed\",\"phase\":\"query\",\"grouped\":true,\"failed_shards\":[{\"shard\":-1,\"index\":null,\"reason\":{\"type\":\"search_context_missing_exception\",\"reason\":\"No search context found for id [10256]\"}},{\"shard\":-1,\"index\":null,\"reason\":{\"type\":\"search_context_missing_exception\",\"reason\":\"No search context found for id [10257]\"}}],\"caused_by\":{\"type\":\"search_context_missing_exception\",\"reason\":\"No search context found for id [10257]\"}},\"status\":404},\"statusCode\":404,\"headers\":{\"date\":\"Fri, 05 Nov 2021 18:21:27 GMT\",\"content-type\":\"application/json; charset=UTF-8\",\"content-length\":\"711\",\"connection\":\"keep-alive\",\"access-control-allow-origin\":\"*\"},\"warnings\":null,\"meta\":{\"context\":null,\"request\":{\"params\":{\"method\":\"GET\",\"path\":\"/_search/scroll/DnF1ZXJ5VGhlbkZldGNoAgAAAAAAACgQFlNkdlJuVjM3UjdLLWhOZjd2TlhmbEEAAAAAAAAoERZTZHZSblYzN1I3Sy1oTmY3dk5YZmxB\",\"body\":\"\",\"querystring\":\"scroll=3m\",\"headers\":{\"User-Agent\":\"elasticsearch-js/5.6.22 (linux 4.14.248-189.473.amzn2.x86_64-x64; Node.js v12.22.7)\",\"Content-Length\":\"0\"},\"timeout\":50000},\"options\":{\"warnings\":null},\"id\":2},\"name\":\"elasticsearch-js\",\"connection\":{\"url\":\"https://vpc-jl-tf-es-vpc-2lkv2q63z7rln5syilzh4hvnjy.us-east-1.es.amazonaws.com/\",\"id\":\"https://vpc-jl-tf-es-vpc-2lkv2q63z7rln5syilzh4hvnjy.us-east-1.es.amazonaws.com/\",\"headers\":null,\"deadCount\":0,\"resurrectTimeout\":0,\"_openRequests\":0,\"status\":\"alive\",\"roles\":{\"master\":true,\"data\":true,\"ingest\":true,\"ml\":false}},\"attempts\":0,\"aborted\":false}}}",
    "sender": "@api/lambdas/create-reconciliation-report",
    "timestamp": "2021-11-05T18:21:27.034Z"
}
```
with errorify(error):
```
{
    "level": "error",
    "message": "{\"stack\":\"ResponseError: search_phase_execution_exception\\n    at IncomingMessage.<anonymous> (/home/task/lambda-function/es-client/node_modules/@elastic/elasticsearch/lib/Transport.js:289:1)\\n    at IncomingMessage.emit (events.js:326:22)\\n    at IncomingMessage.EventEmitter.emit (domain.js:483:12)\\n    at endReadableNT (_stream_readable.js:1241:12)\\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)\",\"message\":\"search_phase_execution_exception\",\"name\":\"ResponseError\",\"meta\":{\"meta\":{\"name\":\"elasticsearch-js\"}}}",
    "sender": "@api/lambdas/create-reconciliation-report",
    "timestamp": "2021-11-05T18:21:28.239Z"
}
```

2021-11-11 01:51 UTC, jennyhliu commented on example/deployments/cumulus/sandbox.tfvars
> +  create_reconciliation_report_es_scroll_duration = "8m"
I just wanted to add a working example of the configuration which does not use the default values.

2021-11-11 15:47 UTC, flamingbear commented on packages/api/lambdas/create-reconciliation-report.js
> +    log.error(JSON.stringify(error));
It seems totally different, but I verified it does the same thing.  Nice.

2021-11-11 15:47 UTC, flamingbear approved these changes

2021-11-11 15:47 UTC, flamingbear commented
Nice. LGTM

2021-11-12 16:25 UTC, merged