Adds logs surrounding the preparation and launch of asynchronous operations
nasa/cumulus pull request #2726
Opened 2022-02-19 15:32 UTC by flamingbear

**Summary:** Summary of changes

Addresses [CUMULUS-XX: Develop amazing new feature](https://bugs.earthdata.nasa.gov/browse/CUMULUS-XXX)

## Changes

* Detailed list or prose of changes
* ...

## PR Checklist

- [ ] Update CHANGELOG
- [ ] Unit tests
- [ ] Ad-hoc testing - Deploy changes and test manually
- [ ] Integration tests

2022-02-19 17:00 UTC, flamingbear commented
@Jkovarik requested you for your expertise and since we already talked about this.  super low priority unless you begin to see failures with the async integration tests as I'm out all week.

2022-02-25 22:58 UTC, Jkovarik commented
Responding to questions: 

> Is the README.md file at api/ecs/async_operation/README.md still correct? I did not (and cannot) push anything to the cumuluss [sic] repo.

Yes, but incomplete.   We're pushing updates to ECR and targeting that in the `example` project (https://github.com/nasa/cumulus/blob/master/example/cumulus-tf/main.tf#L95) , however the default on cumulus module `async_operation_image`  variable is using the cumuluss variable.

In short, we need to publish cumuluss for users and update the default *and* update our ECR.

2022-02-25 22:59 UTC, Jkovarik commented
> can we discuss what needs to be done to actually release this? (which repos does the docker image need to get to and how does it get there?)

Yes, let's pair Monday

2022-02-25 22:59 UTC, Jkovarik commented
> what do we have to do for SIT?

Update SIT's ECR with the updated image

2022-02-25 23:00 UTC, Jkovarik commented on example/cumulus-tf/variables.tf
> +  default = "39"
As noted in the comments, this needs to be pushed to ECR for our tests to work, and if we want users to use 39, we'll need to push it to cumuluss and update the default in the`cumulus` module.

2022-02-25 23:01 UTC, Jkovarik commented on CHANGELOG.md
> +  - Adds logging to ecs/async-operation Docker conatiner that launches async
I'm not sure this is right, the updates are to the async-operations repo. 

maybe 'Updates default async operation image version to 39 to take advantage of (link to changelog) logging updates'?

2022-02-25 23:01 UTC, Jkovarik requested changes
Minor feedback, changes for CL and pending pairing next week.

2022-02-25 23:07 UTC, Jkovarik commented on CHANGELOG.md
> +  - Adds logging to ecs/async-operation Docker conatiner that launches async
Wihdrawn.    😓

2022-02-25 23:08 UTC, Jkovarik requested changes
This all looks fine, change request is just pending pairing on release.

2022-02-28 23:36 UTC, Jkovarik approved these changes

2022-03-01 00:00 UTC, merged