[CUMULUS-2841] Backport 2725, add integration test (#2729)
nasa/cumulus pull request #2870
Opened 2022-02-28 21:43 UTC by Jkovarik

Co-authored-by: Danielle Peters <danielle.o.peters@nasa.gov>**Summary:** Summary of changes

Addresses [CUMULUS-2841](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2841)

## Changes

** Forward port of integration test changes made in https://github.com/nasa/cumulus/pull/2729

- **CUMULUS-2841**
  - Add integration test to validate PDR node provider that requires password
    credentials succeeds on ingest

## PR Checklist

- [ ] Update CHANGELOG
- [ ] Unit tests
- [ ] Ad-hoc testing - Deploy changes and test manually
- [ ] Integration tests

2022-03-08 16:53 UTC, flamingbear requested changes
Two minor nits and request for a clean script.
Also, the seed files are kinda large, you could definitely just change the contents to be strings of 'sample met file' and 'sample hdf' file which would mean we move fewer bytes on set up, but that's also just a suggestion.

2022-03-08 16:53 UTC, flamingbear commented on example/cumulus-tf/iam.tf
> +data "aws_s3_bucket" "fake_s3_pftp_host_configuration_bucket" {
It did not, should it just be ftp?

2022-03-08 16:56 UTC, Jkovarik commented on example/lambdas/ftpPopulateTestLambda/package.json
> +  "version": "9.4.1",
Actually the release script will not catch it unless it's up to date.   Will fix.   Functionally it doesn't matter, but for consistency we should.

2022-03-09 17:30 UTC, Jkovarik commented on example/cumulus-tf/iam.tf
> +data "aws_s3_bucket" "fake_s3_pftp_host_configuration_bucket" {
c75d8ea572

2022-03-09 17:41 UTC, Jkovarik commented on example/lambdas/ftpPopulateTestLambda/package.json
> +  "version": "9.4.1",
f5e2557203

2022-03-09 17:46 UTC, Jkovarik commented on example/lambdas/ftpPopulateTestLambda/package.json
> +    "build": "rm -rf dist && mkdir dist && cp -R granules ./dist/granules && ../../../node_modules/.bin/webpack",
5f64a44a31 should be sufficient.   Lerna handles node_modules.

2022-03-09 17:48 UTC, Jkovarik commented on example/lambdas/ftpPopulateTestLambda/index.js
> +    data = fs.readFileSync(file);
On second thought, we're inconsistent in our usage in the codebase, so the consistency argument goes right out the window.    Updated in favor of explicit: 

2e7029f745

2022-03-09 17:50 UTC, Jkovarik commented on example/cumulus-tf/iam.tf
> +data "aws_s3_bucket" "fake_s3_pftp_host_configuration_bucket" {
c75d8ea572

2022-03-09 17:51 UTC, Jkovarik commented
@flamingbear  I believe I've addressed all of the feedback, take a look at let me know what you think.

2022-03-09 18:20 UTC, flamingbear commented on example/lambdas/ftpPopulateTestLambda/package.json
> +  "version": "9.4.1",
The actual dependencies will work with lerna ?

2022-03-09 18:41 UTC, Jkovarik commented on example/lambdas/ftpPopulateTestLambda/package.json
> +  "version": "9.4.1",
No, that was just bad.     This should be better: a1bb543e94

It won't functionally matter as we're never actually using the npm modules, but still.

2022-03-10 11:42 UTC, Jkovarik commented
@flamingbear  re: your original fixture comment, 169f750e1e

2022-03-10 19:22 UTC, merged