Merge main to feature/rds-phase-2
nasa/cumulus pull request #2876
Opened 2022-03-02 22:41 UTC by botanical

Co-authored-by: Jennifer Tran <12633533+botanical@users.noreply.github.com>**Summary:** Summary of changes

Addresses [CUMULUS-XX: Develop amazing new feature](https://bugs.earthdata.nasa.gov/browse/CUMULUS-XXX)

## Changes

* Detailed list or prose of changes
* ...

## PR Checklist

- [ ] Update CHANGELOG
- [ ] Unit tests
- [ ] Ad-hoc testing - Deploy changes and test manually
- [ ] Integration tests

2022-03-08 22:30 UTC, markdboyd requested changes
Just a few very minor requested changes to unit tests. Great work!

2022-03-08 22:30 UTC, markdboyd commented on CHANGELOG.md
> +- **CUMULUS-2846**
I think I would expect to see these CHANGELOG lines from `master` here?

https://github.com/nasa/cumulus/blame/master/CHANGELOG.md#L29-L32

2022-03-08 22:30 UTC, markdboyd commented on CHANGELOG.md
> +- **CUMULUS-2846**
Nevermind. It seems like the reason why is that these changes are from `master` before 2845 was merged into it. And we shouldn't add the latest from `master` into this PR, we'll just do another PR subsequently.

2022-03-08 22:30 UTC, markdboyd commented on packages/api/tests/endpoints/test-rules.js
> +  t.truthy(originalPgRecord.arn);
```suggestion
  t.truthy(originalPgRecord.arn);
  t.truthy(originalEsRecord.rule.arn);
```

2022-03-08 22:30 UTC, markdboyd commented on packages/api/tests/endpoints/test-rules.js
> +  t.truthy(originalDynamoRule.rule.logEventArn);
```suggestion
  t.truthy(originalDynamoRule.rule.arn);
  t.truthy(originalDynamoRule.rule.logEventArn);
  t.truthy(originalEsRecord.rule.arn);
  t.truthy(originalEsRecord.rule.logEventArn);  
```

2022-03-08 22:30 UTC, markdboyd commented on packages/api/tests/endpoints/test-rules.js
> +  t.deepEqual(originalPgRecord.meta, expectedMeta);
```suggestion
  t.deepEqual(originalPgRecord.meta, expectedMeta);
  t.deepEqual(originalEsRecord.meta, expectedMeta);
```

2022-03-08 22:30 UTC, markdboyd commented on packages/api/tests/endpoints/test-rules.js
> +  t.truthy(originalDynamoRule.rule.arn);
```suggestion
  t.truthy(originalDynamoRule.rule.arn);
  t.truthy(originalEsRecord.rule.arn);
```

2022-03-08 22:30 UTC, markdboyd commented on packages/api/tests/endpoints/test-rules.js
> +  t.truthy(originalDynamoRule.rule.arn);
```suggestion
  t.truthy(originalDynamoRule.rule.arn);
  t.truthy(originalEsRecord.rule.arn);
```

2022-03-09 20:15 UTC, botanical commented on packages/api/tests/endpoints/test-rules.js
> +  t.truthy(originalDynamoRule.rule.arn);
🙇 thank you so much for adding these

2022-03-09 22:20 UTC, markdboyd approved these changes

2022-03-09 23:04 UTC, merged