CUMULUS-2864: ingest granule does not perform separate validation request
nasa/cumulus pull request #2897
Opened 2022-03-16 17:30 UTC by jennyhliu

**Summary:** Summary of changes

Addresses [CUMULUS-2864: Posting to CMR needlessly performs separate validation request](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2864)

## Changes

* Detailed list or prose of changes
* ...

## PR Checklist

- [ ] Update CHANGELOG
- [ ] Unit tests
- [ ] Ad-hoc testing - Deploy changes and test manually
- [ ] Integration tests

2022-03-18 19:56 UTC, flamingbear requested changes
Everything looks good except for one .only to get removed 

I validated the behavior of `got.put` myself.

2022-03-18 19:56 UTC, flamingbear commented on packages/cmr-client/src/CMR.ts
> +      return <CMRResponseBody>response.body;
There is no way the PUT can return a 200 with an error on the body? (the old code was wrong?)

2022-03-18 19:56 UTC, flamingbear commented on packages/cmr-client/src/CMR.ts
> +    }
👍

2022-03-18 19:56 UTC, flamingbear commented on packages/cmr-client/src/ingestConcept.ts
> +    throw new Error(errorMessage);
This is nice cleanup, I just can't find where got.put has to throw if it returns an error from the server. (same comment as previous change)

2022-03-18 19:56 UTC, flamingbear commented on packages/cmr-client/tests/test-CMR.js
> +test.serial.only('ingestUMMGranule() returns CMRInternalError when CMR is down', async (t) => {
remove `.only`

2022-03-18 19:56 UTC, flamingbear commented on packages/cmr-client/src/CMR.ts
> +      return <CMRResponseBody>response.body;
Your test in test-CMR.js makes me think this is true.

2022-03-18 19:56 UTC, flamingbear commented on packages/cmr-client/src/ingestConcept.ts
> +    throw new Error(errorMessage);
I can't find it, but I validated it.

2022-03-18 19:56 UTC, flamingbear commented on packages/cmr-client/src/CMR.ts
> +      return <CMRResponseBody>response.body;
Yup, I validated

2022-03-18 20:59 UTC, flamingbear approved these changes

2022-03-18 20:59 UTC, flamingbear commented
looks good

2022-03-24 13:25 UTC, jennyhliu commented on example/cumulus-tf/ingest_and_publish_granule_with_orca_workflow.asl.json
> -            "skipMetadataValidation": true,
https://github.com/nasa/cumulus/pull/2892#discussion_r833934666

2022-03-24 14:10 UTC, merged