Add Cumulus archive and Cumulus ingest to Cumulus output module
nasa/cumulus pull request #2920
Opened 2022-04-05 19:01 UTC by amarouane-ABDELHAK

**Summary:** Summary of changes

Allows Cumulus users to request the variables or resources ARNs used bu Cumulus module via `module.cumulus.cumulus_archive.<resource>` or  `module.cumulus.cumulus_ingest.<resource>`
## Changes

* Adding the output section for ingest and archive
## PR Checklist

- [ ] Update CHANGELOG
- [ ] Unit tests
- [ ] Ad-hoc testing - Deploy changes and test manually
- [ ] Integration tests

2022-04-08 04:08 UTC, Jkovarik commented
Thanks for the contribution, we'll take a look!

2022-04-08 04:18 UTC, Jkovarik commented on tf-modules/cumulus/outputs.tf
> +output "cumulus_ingest" {
I'm not certain we're going to want to implicitly expose everything the ingest module is providing over being explicit about the specific outputs, much for the same reasons APIs make deliberate choices to expose outputs.    We don't want to create a situation where refactors (such as making the modules more....modular) result in significant user breaking changes.     I think that's worth a discussion before this is approved.

2022-04-08 04:20 UTC, Jkovarik requested changes
Requesting a discussion before approval.

2022-04-15 14:38 UTC, amarouane-ABDELHAK commented
Breaking variables are expected anyway whenever there is a new upgrade, if Cumulus stopped mirroring something in ingest for example they can put it in a breaking change, an integrator would know since terraform will fail during `tf plan` and show you an output is not mirrored. 
I am not saying delete the straightforward mirrored variables, but sometimes we really need some variables and it won't make sense to add PRs just for each variable needed in the future and wait x months to get it in a release.

2022-10-03 18:38 UTC, Jkovarik commented
closing to remove from active PR list.  Feel free to reopen for discussion.

2022-10-03 18:38 UTC, closed without merging