[Snyk] Security upgrade got from 9.6.0 to 11.8.5
nasa/cumulus pull request #3003
Opened 2022-06-20 01:29 UTC by botanical

<p>This PR was automatically created by Snyk using the credentials of a real user.</p><br /><h3>Snyk has created this PR to fix one or more vulnerable packages in the `npm` dependencies of this project.</h3>

![merge advice](https://app.snyk.io/badges/merge-advice/?package_manager=npm&package_name=got&from_version=9.6.0&to_version=11.8.5&pr_id=2bb4952b-398f-46e6-9ef9-07435147490b&visibility=true&has_feature_flag=false)

#### Changes included in this PR

- Changes to the following files to upgrade the vulnerable dependencies to a fixed version:
    - tasks/discover-granules/package.json

#### Vulnerabilities that will be fixed
##### With an upgrade:
Severity                   | Priority Score (*)                   | Issue                   | Breaking Change                   | Exploit Maturity
:-------------------------:|-------------------------|:-------------------------|:-------------------------|:-------------------------
![medium severity](https://res.cloudinary.com/snyk/image/upload/w_20,h_20/v1561977819/icon/m.png "medium severity")  |  **556/1000**  <br/> **Why?** Recently disclosed, Has a fix available, CVSS 5.4  | Open Redirect <br/>[SNYK-JS-GOT-2932019](https://snyk.io/vuln/SNYK-JS-GOT-2932019) |  Yes  | No Known Exploit 

(*) Note that the real score may have changed since the PR was raised.

<details>
  <summary><b>Commit messages</b></summary>
  </br>
  <details>
    <summary>Package name: <b>got</b></summary>
    The new version differs by 250 commits.</br>
    <ul>
      <li><a href="https://snyk.io/redirect/github/sindresorhus/got/commit/5e17bb748c260b02e4cf716c2f4079a1c6a7481e">5e17bb7</a> 11.8.5</li>
      <li><a href="https://snyk.io/redirect/github/sindresorhus/got/commit/bce8ce7d528a675bd5a8d996e110b73674e290d2">bce8ce7</a> Backport 861ccd9ac2237df762a9e2beed7edd88c60782dc</li>
      <li><a href="https://snyk.io/redirect/github/sindresorhus/got/commit/8ced19215603f3eda25a9f5dce390f1b152fe9a3">8ced192</a> Fix build</li>
      <li><a href="https://snyk.io/redirect/github/sindresorhus/got/commit/670eb04b5b01622f489277d6fb1dd04a41d3cb51">670eb04</a> 11.8.4</li>
      <li><a href="https://snyk.io/redirect/github/sindresorhus/got/commit/20f29fe3726a4ddd104f557456dbd5275685e879">20f29fe</a> Backport #1543: Initialize globalResponse in case of ignored HTTPError (#2017)</li>
      <li><a href="https://snyk.io/redirect/github/sindresorhus/got/commit/0da732f4650c398f3b2fea672f8916e6c7004c8f">0da732f</a> 11.8.3</li>
      <li><a href="https://snyk.io/redirect/github/sindresorhus/got/commit/9463bb696d4ee909970e3fc609ee40b7644e3f6c">9463bb6</a> Bump cacheable-request dependency (#1921)</li>
      <li><a href="https://snyk.io/redirect/github/sindresorhus/got/commit/0e167b8b9505a7e9e4a4bbe39e9baeb1f5c4a1fd">0e167b8</a> HTTPError code set to &#x27;HTTPError&#x27; #1711 (#1739)</li>
      <li><a href="https://snyk.io/redirect/github/sindresorhus/got/commit/f896aa52abc41fe40d4942da94a0408477358f14">f896aa5</a> 11.8.2</li>
      <li><a href="https://snyk.io/redirect/github/sindresorhus/got/commit/3bd245f1f7f15e9ef8a99036487a47caabd2fd43">3bd245f</a> Instantiate CacheableLookup only when needed (#1529)</li>
      <li><a href="https://snyk.io/redirect/github/sindresorhus/got/commit/a72ed844c6406b12c84fd5cfe6106e65549946e1">a72ed84</a> 11.8.1</li>
      <li><a href="https://snyk.io/redirect/github/sindresorhus/got/commit/4c815c3a609eb74d0eb139414d9996b4f65dc3c0">4c815c3</a> Do not throw on custom stack traces (#1491)</li>
      <li><a href="https://snyk.io/redirect/github/sindresorhus/got/commit/e0cb8206dacf352ce969267209c5c390f0cafabf">e0cb820</a> 11.8.0</li>
      <li><a href="https://snyk.io/redirect/github/sindresorhus/got/commit/f65c9efd2f343dcabc72d0fb235228aea31719f1">f65c9ef</a> Upgrade dependencies</li>
      <li><a href="https://snyk.io/redirect/github/sindresorhus/got/commit/7acd3801ec7dc80dabc41073af1cf2874b1867a1">7acd380</a> Fix for sending files with size &#x60;0&#x60; on &#x60;stat&#x60; (#1488)</li>
      <li><a href="https://snyk.io/redirect/github/sindresorhus/got/commit/6aa86f2494194907f6c6c8b4774dfa1f69df6876">6aa86f2</a> Fix indentation in the readme</li>
      <li><a href="https://snyk.io/redirect/github/sindresorhus/got/commit/3dd227329d260b3c898f3849bf5805df5a1ea343">3dd2273</a> &#x60;beforeRetry&#x60; allows stream body if different from original (#1501)</li>
      <li><a href="https://snyk.io/redirect/github/sindresorhus/got/commit/b1afa2bba9296ebe7647f8eab902b606b828907d">b1afa2b</a> Fix readme example comment (#1505)</li>
      <li><a href="https://snyk.io/redirect/github/sindresorhus/got/commit/390b1451423df610686894194612647abca98dea">390b145</a> Set default value for an options object (#1495)</li>
      <li><a href="https://snyk.io/redirect/github/sindresorhus/got/commit/87dadd53bdef4184ecba1b263a726bba4674c23c">87dadd5</a> Fixed documentation example for &#x60;responseType&#x60; (#1494)</li>
      <li><a href="https://snyk.io/redirect/github/sindresorhus/got/commit/3bf3e3bb6a8f71c24df12eeec00cea1d3e8d4acc">3bf3e3b</a> Add &#x60;lookup&#x60; option documentation (#1483)</li>
      <li><a href="https://snyk.io/redirect/github/sindresorhus/got/commit/c31366b8c279c3cdab31ac5ae91d72ce68280980">c31366b</a> Add a test for #1438 (#1469)</li>
      <li><a href="https://snyk.io/redirect/github/sindresorhus/got/commit/5d629587cfd7a1b8603376b3e814c02395be1204">5d62958</a> 11.7.0</li>
      <li><a href="https://snyk.io/redirect/github/sindresorhus/got/commit/88b32eade80f964c33af2bdf3970779490a7271b">88b32ea</a> Fix a regression where body was sent after redirect</li>
    </ul>

   <a href="https://snyk.io/redirect/github/sindresorhus/got/compare/a45e071e8dc5027ab9c7fad5919195501cd9e9ca...5e17bb748c260b02e4cf716c2f4079a1c6a7481e">See the full diff</a>
  </details>
</details>

Check the changes in this PR to ensure they won't cause issues with your project.

------------

**Note:** *You are seeing this because you or someone else with access to this repository has authorized Snyk to open fix PRs.*

For more information:  <img src="https://api.segment.io/v1/pixel/track?data=eyJ3cml0ZUtleSI6InJyWmxZcEdHY2RyTHZsb0lYd0dUcVg4WkFRTnNCOUEwIiwiYW5vbnltb3VzSWQiOiIyYmI0OTUyYi0zOThmLTQ2ZTYtOWVmOS0wNzQzNTE0NzQ5MGIiLCJldmVudCI6IlBSIHZpZXdlZCIsInByb3BlcnRpZXMiOnsicHJJZCI6IjJiYjQ5NTJiLTM5OGYtNDZlNi05ZWY5LTA3NDM1MTQ3NDkwYiJ9fQ==" width="0" height="0"/>
🧐 [View latest project report](https://app.snyk.io/org/botanical/project/ad15cc36-2bc4-488a-831d-f82b74fa17e8?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;fix-pr)

🛠 [Adjust project settings](https://app.snyk.io/org/botanical/project/ad15cc36-2bc4-488a-831d-f82b74fa17e8?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;fix-pr/settings)

📚 [Read more about Snyk's upgrade and patch logic](https://support.snyk.io/hc/en-us/articles/360003891078-Snyk-patches-to-fix-vulnerabilities)

[//]: # (snyk:metadata:{"prId":"2bb4952b-398f-46e6-9ef9-07435147490b","prPublicId":"2bb4952b-398f-46e6-9ef9-07435147490b","dependencies":[{"name":"got","from":"9.6.0","to":"11.8.5"}],"packageManager":"npm","projectPublicId":"ad15cc36-2bc4-488a-831d-f82b74fa17e8","projectUrl":"https://app.snyk.io/org/botanical/project/ad15cc36-2bc4-488a-831d-f82b74fa17e8?utm_source=github&utm_medium=referral&page=fix-pr","type":"auto","patch":[],"vulns":["SNYK-JS-GOT-2932019"],"upgrade":["SNYK-JS-GOT-2932019"],"isBreakingChange":true,"env":"prod","prType":"fix","templateVariants":["updated-fix-title","priorityScore","merge-advice-badge-shown"],"priorityScoreList":[556]})

---

**Learn how to fix vulnerabilities with free interactive lessons:**

 🦉 [Open Redirect](https://learn.snyk.io/lessons/open-redirect/javascript?loc&#x3D;fix-pr)

2022-06-21 20:32 UTC, Jkovarik approved these changes

2022-06-21 20:32 UTC, Jkovarik requested changes
This is a couple major version change, are we sure there are no impacts?

2022-06-22 22:59 UTC, botanical commented
> This is a couple major version change, are we sure there are no impacts?

I went through the major version Release notes https://github.com/sindresorhus/got/releases/tag/v11.0.0 and all the breaking changes and it doesn't seem to affect the way we use `got`

I also looked at the various v11.x.x releases as well, and no breaking changes. v11.8.5 includes a security fix https://github.com/sindresorhus/got/releases/tag/v11.8.5

Would love a second pair of eyes on the release notes in case I missed something, though! 

@Jkovarik

2022-07-01 13:23 UTC, kkelly51 approved these changes
Thanks for merging them

2022-07-01 14:32 UTC, Jkovarik approved these changes

2022-07-01 15:07 UTC, merged