CUMULUS-2986: Lambda Memory Sizes in Terraform
nasa/cumulus pull request #3086
Opened 2022-08-22 16:11 UTC by Nnaga1

**Summary:** Summary of changes

-Added the option to configure lambda memory sizes with lambda functions that have customizable timeouts enabled.
Addresses [CUMULUS-2986: Develop amazing new feature](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2986)

## Changes

* Detailed list or prose of changes
Added lambda_memory_sizes to variables.tf of terraform modules, and also changed the initialization of memory sizes to look in the lambda_memory_sizes array, which can be configured in terraform.tfvars of cumulus-tf. 

## PR Checklist

- [x] Update CHANGELOG
- [x] Unit tests
- [x] Ad-hoc testing - Deploy changes and test manually
- [ ] Integration tests

2022-08-22 18:13 UTC, chuckwondo commented
@Nnaga1, I suspect you didn't intent to commit the 2 large zip files.

2022-08-22 18:37 UTC, chuckwondo commented
> yes I'm not sure why those were added, looking into getting rid of them now. Essentially all I'm trying to add is the memory_sizes fields into the terraform files (variables.tf and the files that use them).

Perhaps you used `git add .` (with a dot [`.`], rather than specific files) to add files?

2022-09-01 17:12 UTC, Jkovarik requested changes
Great work! 

 I validated the changes work for the listed lambdas and/or looked for anything missing.  There's a couple of comments/minor issues for your review/commentary, let me know what you think.

2022-09-01 17:12 UTC, Jkovarik commented on docs/configuration/task-configuration.md
> +Currently the following values are supported:
~Was files_to_granules left out?   It's not *really* a production lambda in that I wouldn't expect most users are utilizing it as it's really used to make test/example workflows work, but it *is* a deployed resource that comes with Core. 

There's a sensible argument for us moving it to the example project and template repo, but that's probably a separate convo. 

Same thing for fake-processing-task~


*edit nevermind, I see we also didn't add those to the timeout block, and probably had that same discussion*      I'm going to leave this alone in favor of an arch discussion.

2022-09-01 17:12 UTC, Jkovarik commented on docs/configuration/task-configuration.md
> +Currently the following values are supported:
What is missing, however is `add_misssing_checksums` and `update-cmr-access-constraints`.   That's not an issue directly with this PR or this work, but we should probably add them to this and the timeout list.

2022-09-07 22:10 UTC, Jkovarik commented on tf-modules/ingest/post-to-cmr-task.tf
> +  memory_size      = lookup(var.lambda_memory_sizes, "post_to_cmr_task_memory_size", 256)
I think 512 is probably a good improvement for this lambda, and defensible generally.       If we do that we need to note it in the changelog.

2022-09-07 22:11 UTC, Jkovarik commented on CHANGELOG.md
> +=======
This changeset doesn't look correct.

2022-09-07 22:12 UTC, Jkovarik commented on CHANGELOG.md
> +<<<<<<< HEAD
This looks like a bad merge, please fix!

2022-09-07 22:12 UTC, Jkovarik submitted a review, later dismissed
Thanks for addressing my feedback -- there's still a merge issue that needs sorted, then this looks good to go.

2022-09-21 15:28 UTC, kkelly51 commented on CHANGELOG.md
> +>>>>>>> master
oop delete this line

2022-09-21 15:49 UTC, kkelly51 approved these changes
Looks good!

2022-09-21 19:50 UTC, merged