[CUMULUS-3201] Add new checksumType to LZARDs backup task
nasa/cumulus pull request #3299
Opened 2023-03-08 23:55 UTC by botanical

**Summary:** Summary of changes

Addresses [CUMULUS-XX: Develop amazing new feature](https://bugs.earthdata.nasa.gov/browse/CUMULUS-XXX)

## Changes

* Detailed list or prose of changes
* ...

## PR Checklist

- [ ] Update CHANGELOG
- [ ] Unit tests
- [ ] Ad-hoc testing - Deploy changes and test manually
- [ ] Integration tests

2023-03-14 13:20 UTC, jennyhliu requested changes
Can you add 'sha512' (sha256 as well) to lzardsBackup integration test (LzardsBackupSpec.js or LzardsBackupWorkflowSpec.js)?
Also, can we ingest granule with checksum type 'sha512' and 'sha256' in the payload?

2023-03-14 13:20 UTC, jennyhliu commented on CHANGELOG.md
> +- **CUMULUS-3201**
move to 'Unreleased'

2023-03-15 15:07 UTC, jennyhliu commented
Suggest to update `IngestGranuleSuccessSpec` to use `IngestAndPublishGranuleWithOrca` (since orca is always enabled now), and set different checksumTypes in the input payload, and verify everything works as expected.

2023-03-16 22:42 UTC, botanical commented on example/spec/parallel/lzardsBackup/LzardsBackupSpec.js
> -                      checksumType: 'md5',
https://github.com/nasa/cumulus/pull/3299/commits/5ed07abd06e3c4bf6f2279a1aa5c32fb0e60aff7

2023-03-16 23:05 UTC, botanical commented
> Can you add 'sha512' (sha256 as well) to lzardsBackup integration test (LzardsBackupSpec.js or LzardsBackupWorkflowSpec.js)? Also, can we ingest granule with checksum type 'sha512' and 'sha256' in the payload? Maybe add these checksumType to the payload for IngestAndPublishGranuleWithOrca, so we can verify everything works?

What I did was update the IngestGranule payload that several of our integration tests use to include the various checksums. Let me know what you think @jennyhliu

2023-03-17 17:20 UTC, jennyhliu approved these changes
nice work

2023-03-17 21:30 UTC, merged