Cumulus 3291 coverage minimums
nasa/cumulus pull request #3369
Opened 2023-05-03 14:39 UTC by etcart

**Summary:** Summary of changes

incorporate coverage tests into bamboo automated tests
set minimums to prevent regression

## Changes

* Detailed list or prose of changes
* ...

## PR Checklist

- [ ] Update CHANGELOG
- [ ] Unit tests
- [ ] Ad-hoc testing - Deploy changes and test manually
- [ ] Integration tests

2023-05-18 16:01 UTC, Jkovarik commented on bamboo/unit-tests.sh
> +docker exec -i ${container_id}\_build_env_1 /bin/bash -c "cd $UNIT_TEST_BUILD_DIR && npm run test:coverage"
We should have an arch (or team if there's a hurry)  briefing re: these changes before merging.

2023-05-18 16:01 UTC, Jkovarik requested changes
Requesting we not merge this before a team briefing/walkthrough.

2023-05-18 16:21 UTC, etcart commented
> Requesting we not merge this before a team briefing/walk through.

that sounds reasonable to me, thanks

2023-06-01 15:20 UTC, Jkovarik commented on README.md
> +These tests will fail if coverage drops below certain thresholds.
Nit: fails if coverage drops *or* the unit test fails.

2023-06-01 15:21 UTC, Jkovarik approved these changes
Approving as-is, with the caveat that I'm relying on CI to validate the nyc configurations pass against current main, however there are a couple of minor bits of feedback for your consideration.     Great work!

2023-06-01 16:52 UTC, Jkovarik approved these changes

2023-06-06 03:05 UTC, merged