Release 16.0.0
nasa/cumulus pull request #3376
Opened 2023-05-10 18:57 UTC by Jkovarik

**Summary:** Summary of changes

Addresses [CUMULUS-XX: Develop amazing new feature](https://bugs.earthdata.nasa.gov/browse/CUMULUS-XXX)

## Changes

* Detailed list or prose of changes
* ...

## PR Checklist

- [ ] Update CHANGELOG
- [ ] Unit tests
- [ ] Ad-hoc testing - Deploy changes and test manually
- [ ] Integration tests

2023-05-11 17:54 UTC, npauzenga requested changes
Looks good @Jkovarik! I just had a couple suggestions on the changelog.

2023-05-11 17:54 UTC, npauzenga commented on CHANGELOG.md
> +When migrating directly to v16 from prior releasesolder that V15, please make sure to
```suggestion
When updating directly to v16 from prior releases older that V15, please make sure to
```

2023-05-11 17:54 UTC, npauzenga commented on CHANGELOG.md
> +read through all prior release migrations.
```suggestion
read through all prior release notes.
```
Just being careful about the word "migration" unless that's actually what we mean here.

2023-05-11 17:54 UTC, npauzenga commented on CHANGELOG.md
> +Notable migration concerns since the last PI release version (11.1.x):
Seems like legit "migration" concerns 😄

2023-05-11 17:54 UTC, npauzenga commented on CHANGELOG.md
> +### RDS Phase 3
Duplicate header

2023-05-11 17:54 UTC, npauzenga commented on CHANGELOG.md
> +[unreleased]: https://github.com/nasa/cumulus/compare/v15.0.3...v16.0.0
```suggestion
[v16.0.0]: https://github.com/nasa/cumulus/compare/v15.0.3...v16.0.0
```

2023-05-12 21:04 UTC, Jkovarik commented on CHANGELOG.md
> +[unreleased]: https://github.com/nasa/cumulus/compare/v15.0.3...v16.0.0
🤦🏻  Good catch!

2023-05-12 21:09 UTC, Jkovarik commented on CHANGELOG.md
> +### RDS Phase 3
Header still needed, but wording de-duped: d463fe5925

2023-05-18 15:04 UTC, npauzenga approved these changes
Looks great @Jkovarik

2023-05-18 16:17 UTC, merged