CUMULUS-3076: Add Workflow Message Granule Writes docs
nasa/cumulus pull request #3390
Opened 2023-05-23 14:34 UTC by Jkovarik

**Summary:** Summary of changes

Addresses [CUMULUS-3076](https://bugs.earthdata.nasa.gov/browse/CUMULUS-3076)

## Changes

* Updates/adds documentation on the conditional Message Granule Write logic/feature.      This is designed to better document/cover the existing code logic so as to make the behavior of Core more transparent to end users. 

## PR Checklist

- [ ] Update CHANGELOG
- [ ] Unit tests
- [ ] Ad-hoc testing - Deploy changes and test manually
- [ ] Integration tests

2023-05-24 18:41 UTC, npauzenga requested changes
Looks good @Jkovarik! Just a couple suggestions for clarity but not intending to change any meaning.

2023-05-24 18:41 UTC, npauzenga commented on docs/workflows/message_granule_writes.md
> +The `sfEventSqsToDbRecords` is then triggered in batches of 10 messages each, which correspond to lambda invocations or workflow events, and the corresponding execution/PDR is attempted to write, the
```suggestion
Messages on the `sfEventSqsToDbRecordsInputQueue` (which correspond to lambda invocations or workflow events) are processed in batches of 10 and the `sfEventSqsToDbRecords` Lambda is triggered for each. The corresponding execution/PDR is attempted to write, then the granule records associated with the message are also attempted to be written.
```

2023-05-24 18:41 UTC, npauzenga commented on docs/workflows/message_granule_writes.md
> +For each granule in the batch of granules one of the following occurs:
```suggestion
For each granule in the batch of granules **one of the following** occurs:
```

2023-05-24 18:41 UTC, npauzenga commented on docs/workflows/message_granule_writes.md
> +- The lambda fails to write the granule in an unexpected way (e.g. lambda failure, AWS outage, etc).   In this case, the granule will become visible again after the `sfEventSqsToDbRecordsInputQueue`
```suggestion
- The lambda fails to write the granule in an unexpected way (e.g. lambda failure, AWS outage, etc).   In this case, the granule will become visible again after the `sfEventSqsToDbRecordsInputQueue` visibility timeout (currently set as a function of the rds_connection_timing_configuration terraform variable:
```

2023-05-24 18:41 UTC, npauzenga commented on docs/workflows/message_granule_writes.md
> +- The granule fails to write due to a schema violation, database connection issue or other expected/trapped error.    The message is immediately written to the [Dead Letter Archive](https://nasa.gith
```suggestion
- The granule fails to write due to a schema violation, database connection issue or other expected/caught error.    The message is immediately written to the [Dead Letter Archive](https://nasa.github.io/cumulus/docs/features/dead_letter_archive/) for manual intervention/investigation.
```

2023-05-24 18:41 UTC, npauzenga commented on docs/workflows/message_granule_writes.md
> +- `granuleId` must be unique.
What actually happens if it's not unique? The write will fail because ElasticSearch indexing fails?

2023-05-24 18:41 UTC, npauzenga commented on docs/workflows/message_granule_writes.md
> +- Message granule must match the API schema.
```suggestion
- Message granule must match the API Granule schema.
```
link maybe?

2023-05-24 18:41 UTC, npauzenga commented on docs/workflows/message_granule_writes.md
> +  If not the write will be rejected, the granule status will be updated to failed, and the message will wind up in the [Dead Letter Archive](https://nasa.github.io/cumulus/docs/features/dead_letter_a
```suggestion
  If not the write will be rejected, the granule status will be updated to `failed`, and the message will wind up in the [Dead Letter Archive](https://nasa.github.io/cumulus/docs/features/dead_letter_archive/)
```

2023-05-24 18:41 UTC, npauzenga commented on docs/workflows/message_granule_writes.md
> +- If the granule is being updated to a running/queued state:
```suggestion
- If the granule is being updated to a `running`/`queued` status:
```

2023-05-24 18:41 UTC, npauzenga commented on docs/workflows/message_granule_writes.md
> +  - Only `status`, `timestamp`, `updated_at` and `created_at` are updated.   All other values are retained as-they currently exist in the database.
```suggestion
  - Only `status`, `timestamp`, `updated_at` and `created_at` are updated.   All other values are retained as they currently exist in the database.
```

2023-05-30 20:36 UTC, Jkovarik commented on docs/workflows/message_granule_writes.md
> +- Message granule must match the API schema.
Good suggestion: 39db55f39c

2023-05-30 20:37 UTC, Jkovarik commented
@npauzenga  Thanks for the feedback!   I've addressed your comments, please let me know what you think!

2023-06-02 17:26 UTC, merged