revert CUMULUS-3540
nasa/cumulus pull request #3546
Opened 2024-01-12 15:33 UTC by etcart

This reverts CUMULUS-3540, turning back on previously failing interfaces with cmr in integration tests

* correctly un-stub functions in integration-tests/cmr.js
  * getOnlineResources
  * conceptExists
  * waitForConceptExistsOutcome
* turn back on postToCmr sub-tests 

## PR Checklist

- [ ] Update CHANGELOG
- [ ] Unit tests
- [ ] Ad-hoc testing - Deploy changes and test manually
- [ ] Integration tests

2024-01-30 13:57 UTC, Jkovarik commented
Note: this is reverting https://github.com/nasa/cumulus/pull/3543

2024-01-30 13:59 UTC, Jkovarik commented
The revert being referred to here is https://github.com/nasa/cumulus/pull/3543

2024-01-30 14:01 UTC, Jkovarik commented
Ticket is https://bugs.earthdata.nasa.gov/browse/CUMULUS-3540 , linked ticket is  https://bugs.earthdata.nasa.gov/browse/CUMULUS-3555

2024-01-30 14:10 UTC, etcart commented
other way around, this ticket is CUMULUS-3555, reverting to CUMULUS-3540, I'll make that clearer in the description

2024-01-30 14:15 UTC, Jkovarik requested changes
Looks good, there are a couple of changes that are *additional* to a revert of #3544, and we should have a CL like what we had in that PR noting the change back/remove the entry if it wasn't included in a release.

2024-01-30 14:15 UTC, Jkovarik commented on example/cumulus-tf/lambdas.tf
> +  memory_size      = 512
This mod should be included in the CL.   I realize it's not user facing, but it's project facing nonetheless.

2024-01-30 14:15 UTC, Jkovarik commented on package.json
> +    "@babel/core": "^7.23.2",
What was the reason for this update?   CL entry with details please.

2024-01-30 14:15 UTC, Jkovarik commented on tasks/orca-copy-to-archive-adapter/package.json
> +    "lodash": "^4.17.19"
What was the reason for uppinning this?   CL entry/etc, please.

2024-01-31 05:30 UTC, Jkovarik approved these changes
Looks good to me - thanks for the updates

2024-01-31 13:56 UTC, merged