CUMULUS-3239 - Update Executions LIST endpoint to query Postgres basic
nasa/cumulus pull request #3684
Opened 2024-06-05 19:22 UTC by Nnaga1

**Summary:** Summary of changes

Addresses [CUMULUS-XX: Develop amazing new feature](https://bugs.earthdata.nasa.gov/browse/CUMULUS-XXX)

## Changes

* Detailed list or prose of changes
* ...

## PR Checklist

- [ ] Update CHANGELOG
- [ ] Unit tests
- [ ] Ad-hoc testing - Deploy changes and test manually
- [ ] Integration tests

2024-06-11 20:34 UTC, etcart reviewed
I don't feel comfortable confirming this yet, these are really nits and questions, but I'm looking into it further and trying to understand to give a more proper review

2024-06-11 20:34 UTC, etcart commented on packages/db/src/search/ExecutionSearch.ts
I think there's some refinement here. many of these fields seem redundant w/r to postgresExecutionRecord

2024-06-11 20:34 UTC, etcart commented on packages/db/src/search/ExecutionSearch.ts
> +  cumulus_id: number,
is this here for verbose clarity? or is this not redefinition without change

2024-06-11 20:34 UTC, etcart commented on packages/db/src/search/ExecutionSearch.ts
> +  asyncOperationId: string,
this breaks the pattern of snake_case, can it be changed or does it need to be camel case?

2024-06-27 20:20 UTC, jennyhliu commented on packages/db/src/search/field-mapping.ts
> +  workflowName: (value?: string) => ({
`type` is the api field for workflow name

2024-06-27 20:20 UTC, jennyhliu commented on packages/db/src/search/field-mapping.ts
> +  finalPayload: (value?: string) => ({
I think finalPayload and originalPayload are object in schema, and not queryable.

2024-06-27 20:20 UTC, jennyhliu commented on packages/db/src/search/field-mapping.ts
> +  asyncOperationId: (value?: string) => ({
This is a field needing join with another table.  Can you move the field to the end, and make a comment as in granuleMapping? `// The following fields require querying other tables`

2024-06-27 20:20 UTC, jennyhliu commented on packages/db/src/search/field-mapping.ts
> +  parentCumulusId: (value?: string) => ({
id, url, parentCumulusId are not api fields, e.g. parentArn is the api field

2024-06-27 23:50 UTC, jennyhliu requested changes

2024-06-27 23:50 UTC, jennyhliu commented on packages/db/src/translate/executions.ts
>  export const translatePostgresExecutionToApiExecution = async (
Update translatePostgresExecutionToApiExecution to call translatePostgresExecutionToApiExecutionWithoutDbQuery without changing the functionality.

2024-06-27 23:50 UTC, jennyhliu commented on packages/db/src/search/ExecutionSearch.ts
> +      const collectionPgRecord = {
You can check if collection_cumulus_id is set, if not collectionId is undefined.

2024-06-27 23:50 UTC, jennyhliu commented on packages/db/src/types/execution.ts
> +export interface PostgresSearchExecutionRecord extends PostgresExecution {
It's probably not necessary, we can just use PostgresExecutionRecord type

2024-06-28 18:19 UTC, jennyhliu commented on packages/db/src/search/ExecutionSearch.ts
> +      .leftJoin(`${this.tableName} as ${this.tableName}-parent`, `${this.tableName}.parent_cumulus_id`, `${this.tableName}-parent.cumulus_id`)
For separating words in the database object name, use underscore _

2024-06-28 18:32 UTC, jennyhliu commented on packages/db/tests/search/test-ExecutionSearch.js
> +      async_operation_cumulus_id: num % 2 === 0 ? t.context.testAsyncOperation.cumulus_id
async_operation_cumulus_id, collection_cumulus_id can also be null

2024-06-28 18:57 UTC, jennyhliu commented on packages/db/tests/search/test-ExecutionSearch.js
> +
add test for search with `parentArn`

2024-06-28 18:57 UTC, jennyhliu commented on packages/db/tests/search/test-ExecutionSearch.js
> +/* failing in CI/ passing locally
Is this resolved?

2024-06-28 18:57 UTC, jennyhliu commented on packages/db/tests/search/test-ExecutionSearch.js
> +  t.is(results.results.length, 10);
Can we verify the execution records returned have the correct contents?

2024-07-02 20:21 UTC, jennyhliu commented on packages/db/src/search/ExecutionSearch.ts
> +        parentArn: `${executionsTable}_parent.arn`,
if `includeFullRecord` or searchParentArn is true, select parentArn

2024-07-02 20:21 UTC, jennyhliu commented on packages/db/src/search/ExecutionSearch.ts
> +    } else {
if `includeFullRecord` is true, leftJoin here, otherwise, don't do joins

2024-07-02 21:22 UTC, jennyhliu commented on packages/db/src/search/ExecutionSearch.ts
> +      });
Can you refer to GranuleSearch?  It should support `this.dbQueryParameters.fields`

2024-07-03 14:05 UTC, jennyhliu commented on packages/db/tests/search/test-ExecutionSearch.js
> +  t.context.testTimeStamp3 = '1800725210000';
How do you get these timestamps? They are not used in execution record?

2024-07-03 14:05 UTC, jennyhliu commented on packages/db/tests/search/test-ExecutionSearch.js
> +
Can you add more parentArn tests, like terms, exists, not?

2024-07-03 14:05 UTC, jennyhliu commented on packages/db/tests/search/test-ExecutionSearch.js
> +
Add includeFullRecord test

2024-07-03 15:06 UTC, jennyhliu commented on packages/db/src/search/ExecutionSearch.ts
> +  arn: string,
PostgresExecutionRecord already inherit arn from PostgresExecution

2024-07-03 15:12 UTC, jennyhliu commented on packages/db/src/search/ExecutionSearch.ts
> +      searchQuery.whereLike(`${this.tableName}.arn`, `%${infix}%`);
[countQuery, searchQuery].forEach((query) => query.whereLike(`${this.tableName}.arn`, `%${infix}%`));

2024-07-03 21:19 UTC, jennyhliu approved these changes
Nice work👍

2024-07-05 16:16 UTC, merged