CUMULUS-3770: Investigate and test phased release approach for ElasticSearch Removal - Executions
nasa/cumulus pull request #3747
Opened 2024-07-25 20:24 UTC by Nnaga1

**Summary:** Summary of changes

Addresses [CUMULUS-XX: Develop amazing new feature](https://bugs.earthdata.nasa.gov/browse/CUMULUS-XXX)

## Changes

* Detailed list or prose of changes
* ...

## PR Checklist

- [ ] Update CHANGELOG
- [ ] Unit tests
- [ ] Ad-hoc testing - Deploy changes and test manually
- [ ] Integration tests

2024-07-26 15:17 UTC, npauzenga commented
@Nnaga1 is this reviewable? I don't see a WIP tag but it looks like it might be in progress still?

2024-07-30 15:30 UTC, etcart requested changes
Im have some questions, but the biggest one is this:
was there a conversation I missed where we decided to go for a split "Search" Postgres functionality that's distinct from main-line Postgres functionality and imitates ES

I'm concerned about ending up in a state a year from now where, for reasons that only make sense as a legacy, we have a "Postgres" bit and a "Postgres pretending to be elasticsearch" bit separated from each other

2024-07-30 15:30 UTC, etcart commented on packages/db/src/search/field-mapping.ts
is it not possible here to re-use the Postgres to api translation tools here?
e.g. packages/db/src/translate/executions.ts
or if the purpose here is to be able to translate single fields, should that go in the translate/exeuctions.ts file

2024-07-30 15:30 UTC, etcart commented on packages/db/src/search/ExecutionSearch.ts
does this Postgres search functionality not belong in the Postgres ExecutionModel?

2024-07-30 15:30 UTC, etcart commented on packages/db/.nycrc.json
I'd like to see increased testing here. the new BaseSearch file has notably low coverage

2024-07-30 15:30 UTC, etcart commented on packages/api/endpoints/executions.js
> -  const granules = await getGranulesForPayload(payload, knex);
I can't find the getGranulesForPayload change,  is this just an update that got missed in a previous change?

2024-07-31 16:17 UTC, closed without merging