CUMULUS-3757: Update granule upsert logic to allow updating collection info
nasa/cumulus pull request #3891
Opened 2024-12-31 00:47 UTC by Nnaga1

**Summary:** Summary of changes

Addresses [CUMULUS-XX: Develop amazing new feature](https://bugs.earthdata.nasa.gov/browse/CUMULUS-XXX)

## Changes

* Detailed list or prose of changes
* ...

## PR Checklist

- [ ] Update CHANGELOG
- [ ] Unit tests
- [ ] Ad-hoc testing - Deploy changes and test manually
- [ ] Integration tests

2025-01-03 17:01 UTC, Jkovarik requested changes
Hey @Nnaga1  good progress/work!    I have a couple of comments/questions/etc    I realize this is still WIP, so take comments in that context.  Happy to pair/talk about any of it!!!!

2025-01-03 19:32 UTC, Jkovarik commented on packages/api/endpoints/granules.js
> +    await updateBatchGranulesCollection(knex, granuleIds, collection.cumulus_id);
@Nnaga1  can you elaborate a bit?   

 I grok that the intent of this endpoint is to bulk update collection to avoid the business logic check the database imposes, but this update will make the postgres/es record out of sync.   I can't recall where we landed on that as an approach - if we *are* avoiding an ES update we need to remove the jsdoc comment (it suggests we're updating ES) and have max amounts of documentation coverage of the endpoint as a feature/api doc.

2025-01-03 19:36 UTC, Jkovarik commented on packages/api/endpoints/granules.js
> +    await pMap(granules, (async (granule) =>
The API has via env vars a 2 connection limit for the knex connection pool - calls that `await` knex action that needs a DB connection attempt to pull and have logic that waits for (and retries on failure) a connection from the connection pool. 

At some level of concurrency*average query time the 'wait for connection time' will exceed the configured timeouts/overload the connection pool's ability to handle requests and requests will start failing. 

Allowing a larger number of connections increases that throughput at increased database load/memory footprint (and other resources).    We agreed that the client using this would batch, so to some degree that can be controlled with batching/horizontal scaling, but it's probably a useful, *perhaps* needed configuration option if you're allowing unbounded concurrency configuration.

2025-01-03 19:37 UTC, Jkovarik commented on packages/api/tests/endpoints/test-granules-updateGranulesAndFilesCollection.js
> +  const body = response.body;
Apologies, I was reviewing in the IDE. 

This was a suggestion to 

const { message } = response.body

2025-01-03 19:38 UTC, Jkovarik commented on packages/api/endpoints/granules.js
> + * @param {Object} req - express request object
We should enable typing/ts-chec (zod will help with typing the incoming event objects, in theory too)

2025-01-03 19:39 UTC, Jkovarik commented on packages/db/src/lib/granule.ts
> +    await createRejectableTransaction(knex, async (trx) => {
That suggestion was if we're wholesale updating granules to a collection to ensure the ES updates happen before committing the granule updates.      If we're just doing a bulk query to postgres to update rows, I don't believe it's needed.

2025-01-03 19:40 UTC, Jkovarik commented on packages/api/tests/endpoints/test-granules-updateGranulesAndFilesCollection.js
> +      t.true(file.key.includes(collectionId2));
It seemed to be not passing at all, although I did not run a large sample of tests.

2025-01-06 17:35 UTC, Jkovarik commented on packages/api/endpoints/granules.js
> +  bucket: z.string().nonempty(),
nonempty shows as 

```
@deprecated — Use z.string().min(1) instead.
```

Not sure how I feel about that choice on Zod's part (https://github.com/colinhacks/zod/discussions/2847), but we should make it future proof.   Assuming it stays deprecated of course, but per the current release it is.

2025-01-06 17:36 UTC, Jkovarik commented on packages/api/endpoints/granules.js
> +  bucket: z.string().nonempty(),
Although, there's a comment that suggests they reversed that decision?       We should run that down

2025-01-06 17:38 UTC, Jkovarik commented on packages/api/endpoints/granules.js
> +const ApiFileSchema = z.object({
Nit: consider this being something like ApiFileInputSchema - we already have schemas defined in too many places (e.g. DB typing, API TS typing, schema validation in lib/schemas.js)

2025-01-08 15:36 UTC, Jkovarik commented on packages/api/tests/endpoints/test-granules-updateGranulesAndFilesCollection.js
>    // create 10 granules in one collection, 0 in the other
This comment should probably be updated?

2025-01-08 16:21 UTC, Jkovarik requested changes
@Nnaga1  a couple comments per our live convo for your consideration

2025-01-08 16:21 UTC, Jkovarik commented on CHANGELOG.md
> +  - Added endpoints for updating a granules' records' collection and an endpoint for batch patching
We still need to elaborate a bit more here re: what these updates do, 'batch patching' of what, etc (e.g. added an endpoint to allow updates of multiple granules with concurrency controls, or something like that)

2025-01-08 16:21 UTC, Jkovarik commented on packages/api/endpoints/granules.js
> +const patchGranuleMethod = async (req, res) => {
This looks like the abstraction to remove `_returnPatchGranuleStatus` from `patchGranule`, but the difference in name between `patchGranuleMethod` and `patchGranule` is probably confusing without more context.    The docstrings also have the exact same header text. 

Consider something like `patchGranule` for this method and `patchGranuleAndReturnStatus` or something along those lines instead.

2025-01-08 16:21 UTC, Jkovarik commented on packages/api/tests/endpoints/test-granules-updateGranulesAndFilesCollection.js
> + * @param {Knex | Knex.Transaction} knexOrTransaction - DB client or transaction
nit: this is missing the knex param....but.... *probably* in ava tests we can skip the type annotations for the params.  We've not adopted attempting typing in these for a variety of reasons both good and bad.

2025-01-08 16:21 UTC, Jkovarik commented on packages/api/tests/endpoints/test-granules-updateGranulesAndFilesCollection.js
> + * Simulate granule records post-collection-move for database updates test
Nit: be a bit more precise - what does that mean?

2025-01-08 16:21 UTC, Jkovarik commented on packages/api/tests/endpoints/test-granules-updateGranulesAndFilesCollection.js
> +  process.env.CMR_ENVIRONMENT = 'SIT';
Why is this needed?

2025-01-08 16:21 UTC, Jkovarik commented on packages/api/tests/endpoints/test-granules-updateGranulesAndFilesCollection.js
> +  const { TopicArn } = await createSnsTopic(topicName);
It looks like we're creating an SNS topic here, are we using this?     Consider removing

2025-01-08 16:21 UTC, Jkovarik commented on packages/api/tests/endpoints/test-granules-updateGranulesAndFilesCollection.js
> +  // create 10 granules in one collection, 0 in the other
Update comment

2025-01-08 17:05 UTC, Jkovarik requested changes

2025-01-08 17:05 UTC, Jkovarik commented on packages/api/tests/endpoints/test-granules-updateGranulesAndFilesCollection.js
> +test.serial('PATCH /granules/batchPatch successfully updates a batch of granules', async (t) => {
We aren't testing batch updates of other granule fields here and/or that concurrency options are properly handled - should we?

2025-01-08 17:06 UTC, Jkovarik commented on packages/api/endpoints/granules.js
> +  const knex = dbMaxPool ? await getKnexClient({
Yeah - that allows you to define concurrency controls in the top level method (the one looping), but retain just using a default knex object at the original level it was defined if that's acceptable.

2025-01-08 17:08 UTC, Jkovarik commented on packages/api/endpoints/granules.js
> +  bucket: z.string().nonempty(),
Probably.     The later comment suggesting they may be reversing that decision is interesting.   I'm going to vote for leaving it as is for now, if they change their mind again, at worst it's an upgrade annoyance, nothing critical.

2025-01-08 18:21 UTC, Jkovarik commented on packages/api/tests/endpoints/test-granules-updateGranulesAndFilesCollection.js
> +  t.context.movedGranules.push(await simulateGranuleUpdate(knex, t.context.granules,
That's fair, it's a nit, I may be wrong 😅

2025-01-08 18:23 UTC, Jkovarik commented on packages/api/tests/endpoints/test-granules-updateGranulesAndFilesCollection.js
> +test.serial('PATCH /granules/batchPatch successfully updates a batch of granules', async (t) => {
I think it's worth thinking about, particularly as the code evolves  - but at a minimum we should ensure the endpoint specific params are tested.

2025-01-08 18:28 UTC, Jkovarik commented on packages/api/tests/endpoints/test-granules-updateGranulesAndFilesCollection.js
> +  const { TopicArn } = await createSnsTopic(topicName);
Oh, I see, we have an SNS update buried in the granule update logic, and this avoids the need to stub or do something more convoluted.    Got it, thanks for the comment :thumbsup:

2025-01-08 18:42 UTC, Jkovarik commented on packages/es-client/indexer.js
> + * @param  {Object} esClient - Elasticsearch Connection object
Yikes.     Given we're just about to pull it from Core, don't spend *too* long on that.

2025-01-08 18:42 UTC, Jkovarik commented on packages/db/src/lib/granule.ts
> +export const updateBatchGranulesCollection = async (
@Nnaga1  yes -we should unit test this at the package level.

2025-01-08 23:04 UTC, Jkovarik commented on packages/api/endpoints/granules.js
> +  const granuleIds = granules.map((granule) => granule.granuleId);
Performance question: re: size - do we have a limit bound on how big the query can be?   Can this query handle that bound?

2025-01-08 23:05 UTC, Jkovarik commented on packages/api/endpoints/granules.js
> +    await updateBatchGranulesCollection(knex, granuleIds, collection.cumulus_id);
@Nnaga1  - right, I remember having that conversation, but we didn't close the loop on the implementation - this has an unbounded `.map` on it - we need to limit concurrency to avoid overwhelming ES, or write something that does a bulk update, or ...

2025-01-08 23:06 UTC, Jkovarik commented on packages/api/endpoints/granules.js
> + * Update a batch of granule's collectionId to the new collectionId
Nit:

```suggestion
 * Update a batch of granules to change collectionId to a new collectionId
```

2025-01-08 23:07 UTC, Jkovarik commented on packages/api/endpoints/granules.js
> +router.patch('/batchRecords', batchPatchGranulesRecordCollection);
So, really, I was asking does PATCH /apiroot/granules/batchRecords mean something.   Meaning as a user if I look at 

`/granules/batchRecords` does that imply a batch update?   
 
 Naming things is hard, just wanted to have a conversation about it.

2025-01-08 23:13 UTC, Jkovarik commented on packages/api/endpoints/granules.js
> +const patchGranuleMethod = async (req, res) => {
😍  looks good, thank you!

2025-01-09 16:12 UTC, Jkovarik commented on packages/api/endpoints/granules.js
> +  const granuleIds = granules.map((granule) => granule.granuleId);
I don't think postgres concurrency concerns are in play in that you're using a single query to modify the database.     

The issue here is there's complexity in the updates to the granules in that the postgres update is a single, but large batch update query (which likely has a size bound) , and that's happening de-synced from the ES updates.     The ES updates are being done *one at a time*, but with unbounded (but soon to be bounded?) parallelism, which has it's own time/volume bound. 

The question is, "how many granules is too much for the queries to complete in a reasonable amount of time/perf hit/etc?", and to some degree it's non-trivial, as that depends on DB engine performance, payload size in memory and/or how long the ES updates take.       Given the context of this endpoint, which is not general like the patch granule updates, we can probably end-run that a bit by setting a feature-oriented bound at the cost of limiting performance for this operation, else we need to provide tuning options. 


--- 
There's also a valid question of if a query where 

```
knex(granulesTable).whereIn('granule_id', granuleIds).update({ collection_cumulus_id: collectionCumulusId });
```

instead does a lookup of `cumulus_collection_id` for the passed in collection and just does a bulk update to all granules matching that collection is more performant (more on that once the ES component is removed), but I'm not clear on if there's an analog for ES and/or if we're concerned in the context of the feature that in case of failure the ES records can get desynced from postgres.

2025-01-10 15:36 UTC, etcart commented on packages/api/endpoints/granules.js
> +  }
it confuses the stacktrace, if we really need to catch and rethrow without doing anything with it, then can we use `throw error` instead of `throw new Error(error)`
if, for example, I throw a typo into the file indexer.js at line 165 (const collectionI instead of const collectionId)
this is thrown as 
```
 Error {
    message: 'ReferenceError: collectionId is not defined',
  }

  › batchPatchGranulesRecordCollection (/Users/ecarton/cumulus/packages/api/endpoints/granules.js:763:11)
  › moveGranulesInCumulusDatastores (src/index.ts:211:3)
  › moveFilesForAllGranules (src/index.ts:283:3)
  › moveGranules (src/index.ts:404:3)
  › async tests/test-index.js:225:18
```
a misleading error that says collectionId is not defined at the throw new Error(error) line instead of the line it actually happened on in indexer.js

2025-01-10 15:39 UTC, etcart commented on packages/api/endpoints/granules.js
> +    throw new Error(error);
same request on no try catch or , throw error instead of throw new Error(error)

2025-01-10 15:49 UTC, Jkovarik commented on packages/api/endpoints/granules.js
> +  }
💯  to Ethan's comment - unless we're logging there, try/catch with a *new* error obscures the trace.       We can probably just remove the try, unless there's a good reason to keep it or the intention is to add logging.

2025-01-10 15:52 UTC, Jkovarik commented on packages/api/endpoints/granules.js
> +    await mappingFunction(
One last comment/question/clarification

In this setup, we're mapping over a batch of updates.  If one fails, we get no feedback from the endpoint re: the state of individual granules, just <failed batch>.  

Does that work for the upstream branch?       Assuming so, I think we should document that behavior (users may want to not use this without changes) and probably write a ticket to update the endpoint to return success/failed { graunleId, collectionId } arrays via Promise.allSettled (or the sindre implementation of it at least). 

Thoughts, particularly @etcart ?

2025-01-10 18:07 UTC, Jkovarik commented on packages/api/endpoints/granules.js
> +    await mappingFunction(
Discussed this 'in person', documentation is sufficient at this time per @etcart

2025-01-10 18:53 UTC, Jkovarik commented on packages/api/endpoints/granules.js
> +    message: `Successfully wrote granules with Granule Id: ${granuleIds} to Collection Id: ${newCollectionId}`,
Nit/usability: 

Should this be consumable via the upstream caller?  Not critical to the existing feature, but this essentially looks like a log line, not a consumable payload. 

{ message: <>, [granuleIds] }?

2025-01-13 18:06 UTC, merged